const allTerms = [
  { category: "Auditing",
    term: "Adverse opinion",
    definition: "The opinion expressed when the auditor concludes that the financial statements are materially and pervasively misstated and accordingly are not prepared by the applicable financial reporting framework (ordinarily GAAP)." },
  { category: "Auditing",
    term: "Agreed-upon procedures",
    definition: "An attest engagement in which the CPAs agree to perform procedures for a specified party and to issue a report that is restricted to use by that party (and management)." },
  { category: "Auditing",
    term: "Accounting estimate",
    definition: "An approximation of a monetary amount in the absence of a precise means of measurement. This term is used for an amount measured at fair value where there is estimation uncertainty, as well as for other amounts that require estimation." },
  { category: "Auditing",
    term: "Analytical procedures",
    definition: "Evaluations of financial information through analysis of plausible relationships among both financial and nonfinancial data. Analytical procedures also encompass such investigation, as is necessary, of identified fluctuations or relationships that are inconsistent with other relevant information or that differ from expected values by a significant amount." },
  { category: "Auditing",
    term: "Assertions",
    definition: "Representations by management, explicit or otherwise that are embodied in the financial statements, as used by the auditor to consider the different types of potential misstatements that may occur." },
  { category: "Auditing",
    term: "Audit evidence",
    definition: "Information used by the auditor in arriving at the conclusions on which the auditor's opinion is based. Audit evidence includes both information contained in the accounting records underlying the financial statements and other information. The sufficiency of audit evidence is the measure of the quantity of audit evidence. Appropriateness of audit evidence is the measure of the quality of audit evidence; that is, its relevance and its reliability in providing support for the conclusions on which the auditor's opinion is based." },
  { category: "Auditing",
    term: "Audit plan",
    definition: "A description of the nature, timing, and extent of the audit procedures to be performed." },
  { category: "Auditing",
    term: "Audit risk",
    definition: "The risk that the auditor expresses an inappropriate audit opinion when the financial statements are materially misstated. Audit risk is a function of the risks of material misstatement and detection risk." },
  { category: "Auditing",
    term: "Audit strategy",
    definition: "The approach involves determining overall characteristics of an audit that define its scope, its reporting objectives, timing of procedures, and various important factors relating to the audit. When the overall audit strategy has been established, the auditors start the development of a more detailed audit plan to address the various matters identified in the audit strategy." },
  { category: "Auditing",
    term: "Appropriateness (of audit evidence)",
    definition: "The measure of the quality of audit evidence; that is, its relevance and its reliability in providing support for the conclusions on which the auditor's opinion is based." },
  { category: "Auditing",
    term: "Arm's-length transaction",
    definition: "A transaction conducted on such terms and conditions between a willing buyer and a willing seller who are unrelated and are acting independently of each other and pursuing their own best interests." },
  { category: "Auditing",
    term: "The applicable financial reporting framework",
    definition: "The financial reporting framework adopted by management and, when appropriate, those charged with governance in the preparation and fair presentation of the financial statements that are acceptable given the nature of the entity and the objective of the financial statements, or that is required by law or regulation." },
  { category: "Auditing",
    term: "Assurance engagement",
    definition: "An engagement in which an accountant issues a report designed to enhance the degree of confidence of third parties and management about the outcome of an evaluation or measurement of financial statements (subject matter) against an applicable financial reporting framework." },
  { category: "Auditing",
    term: "Attest engagement",
    definition: "An engagement performed by public accountants that requires independence. The attest standards define it as one in which the public accountant's issue an examination, a review, or an agreed-upon procedures report on the subject matter or on an assertion about subject matter that is the responsibility of another party (ordinarily management)." },
  { category: "Auditing",
    term: "Audit report on financial statements",
    definition: "A document designed to communicate the nature of the audit, including responsibilities taken, limitations, and a conclusion as to the fairness of presentation of the financial statements." },
  { category: "Auditing",
    term: "Control risk",
    definition: "The risk that a misstatement that could occur in an assertion about a class of transaction, account balance, or disclosure and that could be material, either individually or when aggregated with other misstatements, will not be prevented, or detected and corrected, on a timely basis by the entity's internal control." },
  { category: "Auditing",
    term: "Comparative financial statements",
    definition: "A complete set of financial statements for one or more prior periods included with current year financial statements of the current period." },
  { category: "Auditing",
    term: "Compliance audit",
    definition: "An audit that emphasizes performing audit procedures to test an organization's compliance with laws and regulations." },
  { category: "Auditing",
    term: "Condensed (summary) financial statements",
    definition: "Historical financial information that is derived from the financial statements but contains less detail, while still providing a structured representation consistent with the financial statements." },
  { category: "Auditing",
    term: "Consistency",
    definition: "The concept of using the same accounting principles from year to year so that the successive financial statements issued by a business entity will be comparable." },
  { category: "Auditing",
    term: "Compilation of financial statements",
    definition: "An accounting service that involves the preparation of financial statements from client records. No assurance is provided in a compilation. The current professional standards consider compilations to attest engagements." },
  { category: "Auditing",
    term: "Deficiency in internal control",
    definition: "A deficiency in internal control exists when the design or operation of a control does not allow management or employees, in the normal course of performing their assigned functions, to prevent or detect and correct misstatements on a timely basis. A deficiency in design exists when (a) a control necessary to meet the control objective is missing or (b) an existing control is not properly designed. A deficiency in operation exists when a properly designed control does not operate as designed, or when the person performing the control does not possess the necessary authority or competence." },
  { category: "Auditing",
    term: "Detection risk",
    definition: "The risk that the procedures performed by the auditor to reduce audit risk to an acceptably low level will not detect a misstatement that exists, and that could be material, either individually or when aggregated with other misstatements." },
  { category: "Auditing",
    term: "Date of the auditor's report",
    definition: "A date no earlier than the date on which the auditor has obtained sufficient appropriate audit evidence, including evidence that the audit documentation has been reviewed." },
  { category: "Auditing",
    term: "Date of the financial statements",
    definition: "The date of the end of the latest period covered by the financial statements." },
  { category: "Auditing",
    term: "Disclaimer of opinion",
    definition: "An auditor's conclusion in an audit report that he or she is unable to form an opinion on whether the financial statements are prepared by the applicable financial reporting framework (ordinarily GAAP). This conclusion most frequently occurs due to a lack of sufficient appropriate audit evidence. It may also occur due to uncertainties, including going concern uncertainties." },
  { category: "Auditing",
    term: "Emphasis-of-matter paragraph",
    definition: "A paragraph included in the auditor's report that is required by GAAS or is included at the auditor's discretion, and that refers to a matter appropriately presented or disclosed in the financial statement that, in the auditor's professional judgment, is of such importance that it is fundamental to users' understanding of the financial statements." },
  { category: "Auditing",
    term: "Examination",
    definition: "An attest engagement designed to provide the highest level of assurance that CPAs provide on an assertion. An examination of financial statements is referred to as an audit." },
  { category: "Auditing",
    term: "Explanatory paragraph",
    definition: "For a public company, a paragraph inserted in an audit report in which the auditors describe the reasons for giving a report other than a standard report." },
  { category: "Auditing",
    term: "Engagement letter",
    definition: "A formal letter sent by the auditors to the client at the beginning of an engagement summarizing such matters as the nature of the engagement, any limitations on the scope of the audit work, work to be performed by the client's staff, and the basis for the audit fee. The purpose of engagement letters is to avoid misunderstandings." },
  { category: "Auditing",
    term: "Exception (to external confirmation request)",
    definition: "A response that indicates a difference between the information requested to be confirmed, or contained in the entity's records, and information provided by the confirming party." },
  { category: "Auditing",
    term: "External confirmation",
    definition: "Audit evidence obtained as a direct written response to the auditor from a third party (the confirming party), either in paper form or by electronic or another medium." },
  { category: "Auditing",
    term: "Fraud",
    definition: "An intentional act by one or more individuals among management, those charged with governance, employees, or third parties, involving the use of deception that results in a misstatement in financial statements that are subject to an audit. For financial statement audits, fraud includes two types of intentional misstatements — misstatements arising from fraudulent financial reporting and misstatements arising from misappropriation of assets." },
  { category: "Auditing",
    term: "Fraud risk factors",
    definition: "Events or conditions that indicate an incentive or pressure to perpetrate fraud, provide an opportunity to commit fraud, or indicate attitudes or rationalizations to justify a fraudulent action." },
  { category: "Auditing",
    term: "Fraudulent financial reporting",
    definition: "Material misstatement of financial statements by management with the intent to mislead financial statement users. Also called management fraud or cooking the books." },
  { category: "Auditing",
    term: "Further audit procedures",
    definition: "The additional procedures that are performed based on the results of the auditors' risk assessment procedures. Such procedures include (1) tests of controls (if needed), (2) detailed tests of transactions, balances, and disclosures, and (3) substantive analytical procedures." },
  { category: "Auditing",
    term: "General-purpose financial statements",
    definition: "Financial statements prepared by a general-purpose framework." },
  { category: "Auditing",
    term: "General-purpose framework",
    definition: "A financial reporting framework designed to meet the common financial information needs of a wide range of users." },
  { category: "Auditing",
    term: "Hypothetical transaction",
    definition: "A transaction or financial reporting issue that does not involve the facts or circumstances of a specific entity." },
  { category: "Auditing",
    term: "Historical financial information",
    definition: "The information expressed in financial terms about a particular entity, derived primarily from that entity's accounting system, about economic events occurring in past periods or about economic conditions or circumstances at points in time in the past." },
  { category: "Auditing",
    term: "Inherent risk",
    definition: "The susceptibility of an assertion about a class of transaction, account balance, or disclosure to a misstatement that could be material, either individually or when aggregated with other misstatements, before consideration of any related controls." },
  { category: "Auditing",
    term: "Internal auditing",
    definition: "An independent, objective assurance and consulting activity designed to add value and improve an organization's operations. It helps an organization accomplish its objective by bringing a systematic, disciplined approach to evaluate and improve the effectiveness of risk management, control, and governance processes." },
  { category: "Auditing",
    term: "Internal control",
    definition: "A process — affected by those charged with governance, management, and other personnel — designed to provide reasonable assurance about the achievement of the entity's objectives about the reliability of financial reporting, effectiveness and efficiency of operations, and compliance with applicable laws and regulations." },
  { category: "Auditing",
    term: "Internal control checklist",
    definition: "One of several methods of describing internal control in audit working papers. Checklists are usually designed so that 'no' answers prominently identify weaknesses in internal control." },
  { category: "Auditing",
    term: "Internal control flowchart",
    definition: "One of several methods of describing internal control in audit working papers. A symbolic representation of a system or series of procedures with each procedure shown in sequence." },
  { category: "Auditing",
    term: "Internal control questionnaire",
    definition: "One of several methods of describing internal control in audit working papers. Questionnaires may either ask (1) open-ended questions or (2) 'yes/no' questions (in which case it, in essence, becomes the same as an internal control checklist)." },
  { category: "Auditing",
    term: "Internal control written narrative",
    definition: "One of several methods of describing internal control in audit working papers. A written summary of internal control for inclusion in audit working paper — generally a memo." },
  { category: "Auditing",
    term: "Limited (negative) assurance",
    definition: "A conclusion by CPAs that, after applying limited investigative techniques to certain information, they are not aware of the need to modify the presentation of the information." },
  { category: "Auditing",
    term: "Letters for underwriters",
    definition: "Deal with matters such as the auditor's independence and the compliance of unaudited data with the requirements of the SEC. These letters are also referred to as 'comfort letters.'" },
  { category: "Auditing",
    term: "Material weakness",
    definition: "A deficiency, or a combination of deficiencies, in internal control, such that there is a reasonable possibility that a material misstatement of the entity's financial statements will not be prevented, or detected and corrected, on a timely basis." },
  { category: "Auditing",
    term: "Materiality",
    definition: "The magnitude of an omission or misstatement of accounting information that, in the light of surrounding circumstances, makes it probable that the judgment of a reasonable person relying on the information would have been changed or influenced by the omission or misstatements." },
  { category: "Auditing",
    term: "Misappropriation of assets (defalcations)",
    definition: "Theft of client assets by an employee or officer of the organization." },
  { category: "Auditing",
    term: "Misstatement",
    definition: "A difference between the amount, classification, presentation, or disclosure of a reported financial statement item and the amount, classification, presentation, or disclosure that is required for the item to be by the applicable financial reporting framework. Misstatements can arise from error or fraud. Types include: (a) Factual misstatements — those about which there is no doubt; (b) Judgmental misstatements — differences arising from the judgments of management concerning accounting estimates the auditor considers unreasonable; (c) Projected misstatements — the auditor's best estimate of misstatements in populations." },
  { category: "Auditing",
    term: "Modified opinion",
    definition: "A qualified opinion, an adverse opinion, or a disclaimer of opinion." },
  { category: "Auditing",
    term: "Negative confirmation request",
    definition: "A request that the confirming party responds directly to the auditor only if the confirming party disagrees with the information provided in the request." },
  { category: "Auditing",
    term: "Nonresponse",
    definition: "A failure of the confirming party to respond, or fully respond, to a positive confirmation request or a confirmation request returned undelivered." },
  { category: "Auditing",
    term: "Noncompliance",
    definition: "Acts of omission or commission by the entity, either intentional or unintentional, which are contrary to the prevailing laws or regulations. Such acts involve transactions entered into by, or in the name of the entity, or on its behalf, by those charged with governance, management, or employees." },
  { category: "Auditing",
    term: "Negative assurance",
    definition: "A conclusion by CPAs that, after applying limited investigative techniques to certain information, they are not aware of the need to modify the presentation of the information." },
  { category: "Auditing",
    term: "Other-matter paragraph",
    definition: "A paragraph included in the auditor's report that is required by GAAS, or is included at the auditor's discretion, and that refers to a matter other than those presented or disclosed in the financial statements that, in the auditor's professional judgment, is relevant to users' understanding of the audit, the auditor responsibilities or the auditor's opinion." },
  { category: "Auditing",
    term: "Pervasive",
    definition: "The effects on financial statements of misstatements or possible effects of misstatements that are undetected due to an inability to obtain sufficient appropriate audit evidence. Pervasive effects on the financial statements are those that, in the auditor's judgment, are not confined to specific elements, accounts or items of the financial statements or, if so confined, represent or could represent a substantial proportion of the financial statements." },
  { category: "Auditing",
    term: "Omitted procedure",
    definition: "An auditing procedure that the auditor considered necessary in the circumstances existing at the date of the audit of financial statements, but which was not performed." },
  { category: "Auditing",
    term: "Professional judgment",
    definition: "The application of relevant training, knowledge, and experience within the context provided by auditing, accounting, and ethical standards, in making informed decisions about the courses of action that are appropriate in the circumstances of the audit engagement." },
  { category: "Auditing",
    term: "Professional skepticism",
    definition: "An attitude that includes a questioning mind, being alert to conditions that may indicate possible misstatement due to fraud or error, and a critical assessment of audit evidence." },
  { category: "Auditing",
    term: "Positive confirmation request",
    definition: "A request that the confirming party responds directly to the auditor providing the requested information or indicating whether the confirming party agrees or disagrees with the information in the request." },
  { category: "Auditing",
    term: "Performance materiality",
    definition: "The amount (or amounts) set by the auditor at less than materiality for the financial statements as a whole to reduce to an appropriately low level the probability that the aggregate of uncorrected and undetected misstatements exceeds materiality for the financial statements as a whole." },
  { category: "Auditing",
    term: "Predecessor auditor",
    definition: "CPA firm that formerly served as an auditor but has resigned from the engagement or has been notified that its services have been terminated." },
  { category: "Auditing",
    term: "Qualified opinion",
    definition: "The opinion expressed when the auditor concludes that the financial statements are prepared in all material respects, per the applicable financial reporting framework (ordinarily GAAP) except for the effects of some limitation in the scope of the audit or some departure from GAAP." },
  { category: "Auditing",
    term: "Reasonable assurance",
    definition: "In the context of an audit of financial statements, a high, but not absolute, level of assurance." },
  { category: "Auditing",
    term: "Related-party transaction",
    definition: "A transaction in which one party can influence significantly the management or operating policies of the other party, to the extent that one of the transacting parties might be prevented from pursuing its separate interests fully." },
  { category: "Auditing",
    term: "Risk assessment procedures",
    definition: "The audit procedures performed to obtain an understanding of the entity and its environment, including the entity's internal control, to identify and assess the risks of material misstatement, whether due to fraud or error, at the financial statement and assertion levels." },
  { category: "Auditing",
    term: "Relevant assertion",
    definition: "A financial statement assertion that has a reasonable possibility of containing a misstatement or misstatements that would cause the financial statements to be materially misstated. The determination of whether an assertion is a relevant assertion is made without regard to the effect of controls." },
  { category: "Auditing",
    term: "Risk of material misstatement",
    definition: "The risk that the financial statements are materially misstated before the audit. This consists of two components, inherent risk, and control risk." },
  { category: "Auditing",
    term: "Scanning",
    definition: "A type of analytical procedure involving the auditor's use of professional judgment to review accounting data to identify significant or unusual items." },
  { category: "Auditing",
    term: "Subsequent events",
    definition: "Events occurring between the date of the financial statements and the date of the auditor's report that require adjustment of, or disclosure in, the financial statements." },
  { category: "Auditing",
    term: "Subsequently discovered facts",
    definition: "Facts that become known to the auditor after the date of the auditor's report that, had they been known to the auditor at that date, may have caused the auditor to amend the auditor's report." },
  { category: "Auditing",
    term: "Substantive procedure",
    definition: "An audit procedure designed to detect material misstatements at the assertion level. Substantive procedures comprise tests of details (classes of transactions, account balances, and disclosures) and substantive analytical procedures." },
  { category: "Auditing",
    term: "Sufficiency (of audit evidence)",
    definition: "The measure of the quantity of audit evidence. The quantity of the audit evidence needed is affected by the auditor's assessment of the risks of material misstatement and also by the quality of such audit evidence." },
  { category: "Auditing",
    term: "Written representation",
    definition: "A written statement by management provided to the auditor to confirm certain matters or to support other audit evidence. Written representations do not include financial statements, the assertions therein, or supporting books and records." },
  { category: "Auditing",
    term: "Significant risk",
    definition: "An identified and assessed risk of material misstatement that, in the auditor's judgment, requires special audit consideration." },
  { category: "Auditing",
    term: "Specialist",
    definition: "An individual or organization possessing expertise in a field other than accounting or auditing, whose work in that field is used by the auditor to assist the auditor in obtaining sufficient appropriate audit evidence." },
  { category: "Auditing",
    term: "Successor auditor",
    definition: "The auditors who have accepted an engagement to replace the CPA firm that formally served as an auditor (the predecessor auditor)." },
  { category: "Auditing",
    term: "Significant deficiency",
    definition: "A deficiency, or a combination of deficiencies, in internal control that is less severe than a material weakness, yet important enough to merit attention by those charged with governance." },
  { category: "Auditing",
    term: "Shared responsibility opinion",
    definition: "An audit report in which the principal auditors decide to refer to another auditor involved with the audit of some component of the company." },
  { category: "Auditing",
    term: "Standard audit report",
    definition: "The wording of an unqualified audit report that includes no modifications for matters such as substantial doubt about going concern status, a change in accounting principle, emphasis of a matter described in the financial statements, or a shared responsibility opinion." },
  { category: "Auditing",
    term: "Those charged with governance",
    definition: "The person(s) or organization(s) with responsibility for overseeing the strategic direction of the entity and the obligations related to the accountability of the entity. This includes overseeing the financial reporting process." },
  { category: "Auditing",
    term: "Tests of controls",
    definition: "An audit procedure designed to evaluate the operating effectiveness of controls in preventing or detecting/correcting material misstatements at the assertion level." },
  { category: "Auditing",
    term: "Tolerable misstatement",
    definition: "The application of performance materiality to a particular sampling procedure. Tolerable misstatement may be the same amount or an amount lower than performance materiality." },
  { category: "Auditing",
    term: "Walk-through",
    definition: "A procedure in which an auditor follows a transaction from origination through the company's processes, including information systems, until it is reflected in the company's financial records, using the same documents and information technology that company personnel use." },
  { category: "Auditing",
    term: "Unmodified opinion",
    definition: "The opinion expressed when the auditor concludes that the financial statements are prepared in all material respects by the applicable financial reporting framework." },

  { category: "Financial Accounting and Reporting",
    term: "Accounting policies",
    definition: "The specific principles, bases, conventions, rules, and practices adopted by an entity in preparing and presenting financial statements." },
  { category: "Financial Accounting and Reporting",
    term: "Accruals concept",
    definition: "In the accruals basis of accounting, items are recognized as assets, liabilities, equity, income, and expenses when they satisfy the definitions and recognition criteria for those elements in the Conceptual Framework. Items of income and expenditure are matched and accounted for in the period in which they were earned or incurred rather than when the cash was received or paid." },
  { category: "Financial Accounting and Reporting",
    term: "Asset",
    definition: "A resource controlled by an entity as a result of past events and from which future economic benefits are expected to flow to the entity." },
  { category: "Financial Accounting and Reporting",
    term: "Asset turnover",
    definition: "Sales compared to capital employed." },
  { category: "Financial Accounting and Reporting",
    term: "Associate",
    definition: "An entity, including an unincorporated entity such as a partnership, in which an investor has significant influence and which is neither a subsidiary nor a joint venture of the investor." },
  { category: "Financial Accounting and Reporting",
    term: "Borrowing costs",
    definition: "Interest and other costs incurred by an entity in connection with the borrowing of funds." },
  { category: "Financial Accounting and Reporting",
    term: "Capital gearing ratio",
    definition: "A measure of the proportion of a company's capital that is debt." },
  { category: "Financial Accounting and Reporting",
    term: "Carrying amount",
    definition: "The amount at which an asset is recognized in the statement of financial position after deducting any accumulated depreciation and accumulated impairment losses." },
  { category: "Financial Accounting and Reporting",
    term: "Cash",
    definition: "Cash on hand and demand deposits." },
  { category: "Financial Accounting and Reporting",
    term: "Cash equivalents",
    definition: "Short-term, highly liquid investments that are readily convertible to known amounts of cash and which are subject to an insignificant risk of changes in value." },
  { category: "Financial Accounting and Reporting",
    term: "Cash flows",
    definition: "Inflows and outflows of cash and cash equivalents." },
  { category: "Financial Accounting and Reporting",
    term: "Cash-generating unit",
    definition: "The smallest identifiable group of assets for which independent cash flows can be identified and measured." },
  { category: "Financial Accounting and Reporting",
    term: "Capital expenditure",
    definition: "Expenditure on non-current assets, the net cost of which is to be 'capitalized' and depreciated over the anticipated useful working life of the assets." },
  { category: "Financial Accounting and Reporting",
    term: "Change in accounting estimate",
    definition: "An adjustment of the carrying amount of an asset or a liability or the amount of the periodic consumption of an asset that results from the assessment of the present status of, and expected future benefits and obligations associated with assets and liabilities." },
  { category: "Financial Accounting and Reporting",
    term: "Comparability",
    definition: "Accounting policies used should be disclosed, to make it possible for users to compare the company's results with its prior years and with the results of other companies." },
  { category: "Financial Accounting and Reporting",
    term: "Conceptual framework",
    definition: "A statement of generally accepted theoretical principles which form the frame of reference for financial reporting." },
  { category: "Financial Accounting and Reporting",
    term: "Consolidated accounts",
    definition: "A form of group accounts which combines the information contained in the separate accounts of a holding company and its subsidiaries as if they were the accounts of a single entity." },
  { category: "Financial Accounting and Reporting",
    term: "Cost model",
    definition: "A non-current asset is carried at its cost less depreciation and any accumulated impairment loss." },
  { category: "Financial Accounting and Reporting",
    term: "Control",
    definition: "The power to govern the financial and operating policies of an entity to obtain benefits from its activities." },
  { category: "Financial Accounting and Reporting",
    term: "Current assets",
    definition: "Assets used in the trading activities of the business, such as inventory, trade receivables and cash in the bank." },
  { category: "Financial Accounting and Reporting",
    term: "Current liabilities",
    definition: "Amounts due in the shorter term, such as trade payables and sales tax." },
  { category: "Financial Accounting and Reporting",
    term: "Current ratio",
    definition: "The ratio of current assets to current liabilities." },
  { category: "Financial Accounting and Reporting",
    term: "Current tax",
    definition: "The amount payable to the tax authorities to the trading activities of the period." },
  { category: "Financial Accounting and Reporting",
    term: "Deductible temporary differences",
    definition: "Temporary differences that will result in amounts that are deductible in determining taxable profit (tax loss) of future periods when the carrying amount of the asset or liability is recovered or settled. These result in a deferred tax asset." },
  { category: "Financial Accounting and Reporting",
    term: "Deferred tax",
    definition: "An accounting measure used to match the tax effects of transactions with their accounting impact and thereby produce less distorted results." },
  { category: "Financial Accounting and Reporting",
    term: "Deferred tax assets",
    definition: "The amounts of income taxes recoverable in future periods in respect of: deductible temporary differences, the carryforward of unused tax losses, and the carryforward of unused tax credits." },
  { category: "Financial Accounting and Reporting",
    term: "Deferred tax liabilities",
    definition: "The amounts of income taxes payable in future periods in respect of temporary taxable differences." },
  { category: "Financial Accounting and Reporting",
    term: "Depreciable amount",
    definition: "When dealing with a depreciable asset, this is the historical cost or other amount substituted for cost in the financial statements, less the estimated residual value." },
  { category: "Financial Accounting and Reporting",
    term: "Depreciable assets",
    definition: "Assets which are expected to be used during more than one accounting period, have a limited useful life, and are held by an entity for use in the production or supply of goods or services, for rental to others, or administrative purposes." },
  { category: "Financial Accounting and Reporting",
    term: "Depreciation",
    definition: "A method of spreading the cost of non-current assets over their useful lives with an annual charge to the statement of comprehensive income." },
  { category: "Financial Accounting and Reporting",
    term: "Development",
    definition: "The application of research findings or other knowledge to a plan or design for the production of new or substantially improved materials, devices, products, processes, systems, or services before the commencement of commercial production or use." },
  { category: "Financial Accounting and Reporting",
    term: "Dividend cover",
    definition: "The ratio of earnings per share to dividend per share." },
  { category: "Financial Accounting and Reporting",
    term: "Dividend yield",
    definition: "The return a shareholder is currently expecting on the shares of a company." },
  { category: "Financial Accounting and Reporting",
    term: "Earnings per share (EPS)",
    definition: "The amount of net profit for the period that is attributable to each ordinary share which is outstanding during all or part of the period." },
  { category: "Financial Accounting and Reporting",
    term: "Economic value (EV), or value in use",
    definition: "What the existing asset will be worth to the company over the rest of its useful life." },
  { category: "Financial Accounting and Reporting",
    term: "Equity",
    definition: "The residual interest in the assets of the entity after deducting all its liabilities." },
  { category: "Financial Accounting and Reporting",
    term: "Equity method",
    definition: "A method of accounting whereby the investment is initially recorded at cost and adjusted after that for the post-acquisition change in the investor's share of net assets of the investee. The profit or loss of the investor includes the investor's share of the profit or loss of the investee." },
  { category: "Financial Accounting and Reporting",
    term: "Exchange difference",
    definition: "The difference resulting from translating a given number of units of one currency into another currency at different exchange rates." },
  { category: "Financial Accounting and Reporting",
    term: "Exchange rate",
    definition: "The ratio of exchange for two currencies." },
  { category: "Financial Accounting and Reporting",
    term: "Expenses",
    definition: "Decreases in economic benefits during the accounting period in the form of outflows or depletions of assets or incurring liabilities that result in decreases in equity, other than those relating to distributions to equity participants." },
  { category: "Financial Accounting and Reporting",
    term: "Faithful representation",
    definition: "Information that is faithfully represented is complete, neutral, and free from error." },
  { category: "Financial Accounting and Reporting",
    term: "Fair value",
    definition: "The amount for which an asset could be exchanged or a liability settled, between knowledgeable, willing parties in an arm's length transaction." },
  { category: "Financial Accounting and Reporting",
    term: "Financial accounting",
    definition: "The accounting processes required for reporting the results and financial position of a business." },
  { category: "Financial Accounting and Reporting",
    term: "Financial reporting",
    definition: "A way of recording, analyzing, and summarizing financial data." },
  { category: "Financial Accounting and Reporting",
    term: "Foreign currency",
    definition: "Currency other than the functional currency of the entity." },
  { category: "Financial Accounting and Reporting",
    term: "Functional currency",
    definition: "The currency of the primary economic environment in which the entity operates." },
  { category: "Financial Accounting and Reporting",
    term: "Gains",
    definition: "Increases in economic benefits. As such, they are no different from revenue." },
  { category: "Financial Accounting and Reporting",
    term: "Generally accepted accounting principles (GAAP)",
    definition: "Signifies all the rules, from whatever source, which govern accounting." },
  { category: "Financial Accounting and Reporting",
    term: "Going concern concept",
    definition: "The entity is normally viewed as a going concern, that is, as continuing in operation for the foreseeable future. It is assumed that the entity has neither the intention nor the necessity of liquidation or of curtailing materially the scale of its operations." },
  { category: "Financial Accounting and Reporting",
    term: "Goodwill",
    definition: "Any excess of the consideration transferred to obtain control of another entity plus the non-controlling interest in that entity over the fair value of the identifiable assets and liabilities of the entity as at the date of the exchange transaction." },
  { category: "Financial Accounting and Reporting",
    term: "Group",
    definition: "A parent and all its subsidiaries." },
  { category: "Financial Accounting and Reporting",
    term: "Historical cost",
    definition: "Assets are recorded at the amount of cash or cash equivalents paid or the fair value of the consideration given to acquire them at the time of their acquisition." },
  { category: "Financial Accounting and Reporting",
    term: "Impairment",
    definition: "A fall in the value of an asset, so that its 'recoverable amount' is now less than its carrying amount in the statement of financial position." },
  { category: "Financial Accounting and Reporting",
    term: "Impairment loss",
    definition: "The amount by which the carrying amount of an asset exceeds its recoverable amount." },
  { category: "Financial Accounting and Reporting",
    term: "Income",
    definition: "Increases in economic benefits during the accounting period in the form of inflows or enhancements of assets or decreases of liabilities that result in increases in equity, other than those relating to contributions from equity participants." },
  { category: "Financial Accounting and Reporting",
    term: "Intangible assets",
    definition: "Non-monetary assets without physical substance." },
  { category: "Financial Accounting and Reporting",
    term: "Interest cover",
    definition: "A ratio that shows whether a company is earning enough profits before interest and tax to pay its interest costs comfortably, or whether its interest costs are high to the size of its profits." },
  { category: "Financial Accounting and Reporting",
    term: "Intra-group trading",
    definition: "Trading/transactions between companies in a group." },
  { category: "Financial Accounting and Reporting",
    term: "Net realizable value",
    definition: "The expected price less any costs still to be incurred in getting the item ready for sale and then selling it." },
  { category: "Financial Accounting and Reporting",
    term: "Non-controlling interest",
    definition: "The shares in a subsidiary that are not owned by the parent company." },
  { category: "Financial Accounting and Reporting",
    term: "Non-current assets",
    definition: "Assets for long-term use within the business." },
  { category: "Financial Accounting and Reporting",
    term: "Non-current liabilities",
    definition: "Long term liabilities usually due after more than one year." },
  { category: "Financial Accounting and Reporting",
    term: "Operating cycle of an entity",
    definition: "The time between the acquisition of assets for processing and their realization in cash or cash equivalents." },
  { category: "Financial Accounting and Reporting",
    term: "Other comprehensive income",
    definition: "Gains and losses which arise in the accounting period but are not included in profit or loss as they are not realized. This includes revaluation gains." },
  { category: "Financial Accounting and Reporting",
    term: "Parent",
    definition: "An entity that has one or more subsidiaries." },
  { category: "Financial Accounting and Reporting",
    term: "Payables payment period",
    definition: "Number of days of credit taken from suppliers." },
  { category: "Financial Accounting and Reporting",
    term: "Post-acquisition profits",
    definition: "Profits earned by a subsidiary since the date of acquisition." },
  { category: "Financial Accounting and Reporting",
    term: "Presentation currency",
    definition: "The currency in which the financial statements are presented." },
  { category: "Financial Accounting and Reporting",
    term: "Price/Earnings (P/E) ratio",
    definition: "The ratio of a company's current share price to the earnings per share." },
  { category: "Financial Accounting and Reporting",
    term: "Prior period errors",
    definition: "Omissions from, and misstatements in, the entity's financial statements for one or more prior periods arising from a failure to use, or misuse of, reliable information that was available when financial statements for those periods were authorized for issue, and could reasonably be expected to have been obtained and taken into account in the preparation." },
  { category: "Financial Accounting and Reporting",
    term: "Profit margin",
    definition: "Profit as a percentage of sales." },
  { category: "Financial Accounting and Reporting",
    term: "Property, plant, and equipment",
    definition: "Tangible assets that are held for use in the production or supply of goods or services, for rental to others, or administrative purposes; and are expected to be used during more than one period." },
  { category: "Financial Accounting and Reporting",
    term: "Provision",
    definition: "A present obligation that satisfies the rest of the definition of a liability, even if the amount of the obligation has to be estimated." },
  { category: "Financial Accounting and Reporting",
    term: "Qualifying asset",
    definition: "An asset that necessarily takes a substantial period to get ready for its intended use or sale." },
  { category: "Financial Accounting and Reporting",
    term: "Quick ratio",
    definition: "The ratio of current assets minus inventory to current liabilities — also known as the acid test ratio." },
  { category: "Financial Accounting and Reporting",
    term: "Realizable value",
    definition: "The amount of cash or cash equivalents that could currently be obtained by selling an asset in an orderly disposal." },
  { category: "Financial Accounting and Reporting",
    term: "Receivables collection period",
    definition: "The number of days taken to collect receivables outstanding." },
  { category: "Financial Accounting and Reporting",
    term: "Recognition",
    definition: "The process of incorporating in the statement of financial position or statement of comprehensive income an item that meets the definition of an element." },
  { category: "Financial Accounting and Reporting",
    term: "Relevance",
    definition: "Relevant financial information is capable of making a difference in the decisions made by users." },
  { category: "Financial Accounting and Reporting",
    term: "Replacement cost",
    definition: "The amount needed to replace an item with an identical item. This is the same as the current cost." },
  { category: "Financial Accounting and Reporting",
    term: "Reporting entity",
    definition: "An entity for which some users rely on the financial statements as their major source of financial information about the entity." },
  { category: "Financial Accounting and Reporting",
    term: "Research",
    definition: "Original and planned investigation undertaken with the prospect of gaining new scientific or technical knowledge and understanding." },
  { category: "Financial Accounting and Reporting",
    term: "Residual value",
    definition: "The net amount which the entity expects to obtain for an asset at the end of its useful life after deducting the expected costs of disposal." },
  { category: "Financial Accounting and Reporting",
    term: "Retrospective application",
    definition: "Applying a new accounting policy to transactions, other events, and conditions as if that policy had always been applied." },
  { category: "Financial Accounting and Reporting",
    term: "Return on capital employed (ROCE)",
    definition: "States the profit as a percentage of the amount of capital employed." },
  { category: "Financial Accounting and Reporting",
    term: "Return on equity (ROE)",
    definition: "States profit as a percentage of shareholders' funds." },
  { category: "Financial Accounting and Reporting",
    term: "Revaluation model",
    definition: "Non-current assets are carried at a revalued amount, being its fair value at the date of the revaluation less any subsequent accumulated depreciation and subsequent accumulated impairment losses." },
  { category: "Financial Accounting and Reporting",
    term: "Revenue",
    definition: "The gross inflow of economic benefits during the period arising in the course of the ordinary activities of an entity when those inflows result in increases in equity, other than increases relating to contributions from equity participants." },
  { category: "Financial Accounting and Reporting",
    term: "Revenue expenditure",
    definition: "Expenditure incurred for the trade of the business or to maintain the existing earning capacity of non-current assets." },
  { category: "Financial Accounting and Reporting",
    term: "Significant influence",
    definition: "The power to participate in the financial and operating policy decisions of an investee or an economic activity but is not control or joint control over those policies." },
  { category: "Financial Accounting and Reporting",
    term: "Solvency",
    definition: "The availability of cash over the long term to meet financial commitments as they fall due." },
  { category: "Financial Accounting and Reporting",
    term: "Statement of changes in equity",
    definition: "Shows the movement in the equity section of the statement of financial position." },
  { category: "Financial Accounting and Reporting",
    term: "Statement of cash flows",
    definition: "A useful addition to the financial statements of a company because accounting profit is not the only indicator of performance. Statements of cash flows concentrate on the sources and uses of cash and are a useful indicator of a company's liquidity and solvency." },
  { category: "Financial Accounting and Reporting",
    term: "Statement of comprehensive income",
    definition: "A statement showing the profit or loss of an entity (being income less expenses) and total comprehensive income (being the profit or loss plus other comprehensive income)." },
  { category: "Financial Accounting and Reporting",
    term: "Statement of financial position",
    definition: "Key financial statement which lists the assets, liabilities, and owners' equity of a business. Sometimes referred to as a balance sheet." },
  { category: "Financial Accounting and Reporting",
    term: "Straight-line depreciation",
    definition: "Where an equal amount of the depreciable amount of an asset is written off in each year of its useful life." },
  { category: "Financial Accounting and Reporting",
    term: "Subsidiary",
    definition: "An entity that is controlled by another entity (known as the parent)." },
  { category: "Financial Accounting and Reporting",
    term: "Substance over form",
    definition: "The principle that transactions and other events are accounted for and presented by their substance and economic reality and not merely their legal form." },
  { category: "Financial Accounting and Reporting",
    term: "The tax base of an asset or liability",
    definition: "The amount attributed to that asset or liability for tax purposes." },
  { category: "Financial Accounting and Reporting",
    term: "Taxable temporary differences",
    definition: "Temporary differences that will result in taxable amounts in determining taxable profit (tax loss) of future periods when the carrying amount of the asset or liability is recovered or settled. These result in deferred tax liabilities." },
  { category: "Financial Accounting and Reporting",
    term: "Trade payables",
    definition: "The amounts due to credit suppliers." },
  { category: "Financial Accounting and Reporting",
    term: "Trade receivables",
    definition: "The amounts owed by credit customers." },
  { category: "Financial Accounting and Reporting",
    term: "Timeliness",
    definition: "Financial information should be available in time to be capable of influencing users' decisions." },
  { category: "Financial Accounting and Reporting",
    term: "Verifiability",
    definition: "Information is verifiable if different observers can broadly agree that a particular way of presenting an item is a faithful representation." },
  { category: "Financial Accounting and Reporting",
    term: "Understandability",
    definition: "Financial information needs to be capable of being understood by users 'having reasonable knowledge of business and economic activities and accounting'." },
  { category: "Financial Accounting and Reporting",
    term: "Useful life",
    definition: "Either the period over which a depreciable asset is expected to be used by the entity, or the number of production or similar units expected to be obtained from the asset by the entity." },

  { category: "Management Accounting and Control",
    term: "Activity-Based Costing (ABC)",
    definition: "An approach to the costing and monitoring of activities which involves tracing resource consumption and costing final outputs. Resources are assigned to activities and activities to cost objects based on consumption estimates." },
  { category: "Management Accounting and Control",
    term: "Administration costs",
    definition: "The costs of managing an organization." },
  { category: "Management Accounting and Control",
    term: "Allocation",
    definition: "The process by which whole cost items are charged directly to a unit or cost center." },
  { category: "Management Accounting and Control",
    term: "Avoidable costs",
    definition: "Costs that would not be incurred if the activity to which they relate did not exist." },
  { category: "Management Accounting and Control",
    term: "Balanced scorecard approach",
    definition: "An approach to the provision of information to management to assist strategic policy formulation and achievement. It emphasizes the need to provide the user with a set of information which addresses all relevant areas of performance in an objective and unbiased fashion, covering areas such as profitability, customer satisfaction, internal efficiency, and learning and growth." },
  { category: "Management Accounting and Control",
    term: "Budget",
    definition: "A quantitative statement, for a defined period, which may include planned revenues, expenses, assets, liabilities, and cash flows." },
  { category: "Management Accounting and Control",
    term: "Budget manual",
    definition: "A collection of instructions governing the responsibilities of persons and the procedures, forms, and records relating to the preparation and use of budgetary data." },
  { category: "Management Accounting and Control",
    term: "By-product",
    definition: "The output of some value produced incidentally while manufacturing the main product." },
  { category: "Management Accounting and Control",
    term: "Cash budget",
    definition: "A statement in which estimated future cash receipts and payments are tabulated in such a way as to show the forecast cash balance of business at defined intervals." },
  { category: "Management Accounting and Control",
    term: "Controllable costs",
    definition: "Items of expenditure which can be directly influenced by a given manager within a given period." },
  { category: "Management Accounting and Control",
    term: "Cost behavior",
    definition: "How costs are affected by changes in the volume of output." },
  { category: "Management Accounting and Control",
    term: "Cost driver",
    definition: "A factor influencing the level of cost. It is often used in the context of ABC to denote the factor which links activity resource consumption to product outputs." },
  { category: "Management Accounting and Control",
    term: "Cost pool",
    definition: "A grouping of costs relating to a particular activity in an activity-based costing system." },
  { category: "Management Accounting and Control",
    term: "Cost, or expense, center",
    definition: "Any part of an organization that incurs costs." },
  { category: "Management Accounting and Control",
    term: "Cost-volume-profit (CVP) analysis",
    definition: "The study of the interrelationships between costs, volume, and profit at various levels of activity." },
  { category: "Management Accounting and Control",
    term: "Customer profitability analysis (CPA)",
    definition: "The analysis of the revenue streams and service costs associated with specific customers or customer groups." },
  { category: "Management Accounting and Control",
    term: "Data",
    definition: "The raw material for data processing. Data relates to facts, events, and transactions." },
  { category: "Management Accounting and Control",
    term: "Development costs",
    definition: "The costs incurred between the decision to produce a new or improved product and the commencement of the full manufacture of the product." },
  { category: "Management Accounting and Control",
    term: "Differential cost",
    definition: "The difference in total cost between alternatives." },
  { category: "Management Accounting and Control",
    term: "Direct cost",
    definition: "A cost that can be traced in full to the product, service, or department that is incurring the cost." },
  { category: "Management Accounting and Control",
    term: "Direct labor costs",
    definition: "The specific costs of the workforce used to make a product or provide a service. Direct labor costs are established by measuring the time taken for a job, or the time taken in 'direct production work.'" },
  { category: "Management Accounting and Control",
    term: "Direct labor efficiency variance",
    definition: "The difference between the hours that should have been worked for the number of units produced, and the actual number of hours worked, valued at the standard rate per hour." },
  { category: "Management Accounting and Control",
    term: "Direct labor rate variance",
    definition: "The difference between the standard cost and the actual cost for the actual number of hours paid for." },
  { category: "Management Accounting and Control",
    term: "Direct material costs",
    definition: "The costs of materials that are known to have been used in making and selling a product or providing a service." },
  { category: "Management Accounting and Control",
    term: "Direct material price variance",
    definition: "The difference between the standard cost and the actual cost for the actual quantity of material used or purchased." },
  { category: "Management Accounting and Control",
    term: "Direct material total variance",
    definition: "The difference between what the output cost and what it should have cost, in terms of material used." },
  { category: "Management Accounting and Control",
    term: "Direct material usage variance",
    definition: "The difference between the standard quantity of materials that should have been used for the number of units produced, and the actual quantity of materials used, valued at the standard cost per unit of material." },
  { category: "Management Accounting and Control",
    term: "Economic Order Quantity (EOQ)",
    definition: "The order quantity which minimizes inventory costs. The EOQ can be calculated using a table, graph, or formula." },
  { category: "Management Accounting and Control",
    term: "Facility-sustaining activities",
    definition: "Activities undertaken to support the organization as a whole and which cannot be logically linked to individual units of output." },
  { category: "Management Accounting and Control",
    term: "Financing costs",
    definition: "Costs incurred to finance business such as loan interest." },
  { category: "Management Accounting and Control",
    term: "Fixed budget",
    definition: "A budget that is set for a single activity level." },
  { category: "Management Accounting and Control",
    term: "Fixed cost",
    definition: "A cost which is incurred for a particular period and which, within certain activity levels, is unaffected by changes in the level of activity." },
  { category: "Management Accounting and Control",
    term: "Fixed overhead expenditure variance",
    definition: "The difference between the budgeted fixed overhead expenditure and actual fixed overhead expenditure." },
  { category: "Management Accounting and Control",
    term: "Fixed overhead total variance",
    definition: "The difference between fixed overhead incurred and fixed overhead absorbed. In other words, it is the under– or over-absorbed fixed overhead." },
  { category: "Management Accounting and Control",
    term: "Fixed overhead volume capacity variance",
    definition: "The difference between budgeted (planned) hours of work and the actual hours worked, multiplied by the standard absorption rate per hour." },
  { category: "Management Accounting and Control",
    term: "Fixed overhead volume efficiency variance",
    definition: "The difference between the number of hours that actual production should have taken, and the number of hours taken (that is, worked) multiplied by the standard absorption rate per hour." },
  { category: "Management Accounting and Control",
    term: "Fixed overhead volume variance",
    definition: "The difference between actual and budgeted (planned) volume multiplied by the standard absorption rate per unit." },
  { category: "Management Accounting and Control",
    term: "Flexible budget",
    definition: "A budget that, by recognizing different cost behavior patterns, is designed to change as the volume of activity changes." },
  { category: "Management Accounting and Control",
    term: "Full cost-plus pricing",
    definition: "A method of determining the sales price by calculating the full cost of the product and adding a percentage mark-up for profit." },
  { category: "Management Accounting and Control",
    term: "Indirect cost, or overhead",
    definition: "A cost that is incurred in the course of making a product, providing a service or running a department, but which cannot be traced directly and in full to the product, service, or department." },
  { category: "Management Accounting and Control",
    term: "Information",
    definition: "Data that has been processed in such a way as to be meaningful to the person who receives it." },
  { category: "Management Accounting and Control",
    term: "Investment center manager",
    definition: "A manager who has some say in investment policy in their area of operations as well as being responsible for costs and revenues." },
  { category: "Management Accounting and Control",
    term: "Job costing",
    definition: "The costing method used where work is undertaken to customers' special requirements, and each order is of comparatively short duration." },
  { category: "Management Accounting and Control",
    term: "Joint products",
    definition: "Two or more products produced by the same process and separated in processing, each having a sufficiently high saleable value to merit recognition as a main product." },
  { category: "Management Accounting and Control",
    term: "Just-in-time (JIT)",
    definition: "A system whose objective is to produce or to procure products or components as they are required by a customer or for use, rather than for stock. A JIT system is a 'pull' system, which responds to demand, in contrast to a 'push' system." },
  { category: "Management Accounting and Control",
    term: "Just-in-time production",
    definition: "A system that is driven by demand for finished products whereby each component on a production line is produced only when needed for the next stage." },
  { category: "Management Accounting and Control",
    term: "Just-in-time purchasing",
    definition: "A system in which material purchases are contracted so that the receipt and usage of material coincide to the maximum extent possible." },
  { category: "Management Accounting and Control",
    term: "Kaizen",
    definition: "A Japanese term for continuous improvement in all aspects of an entity's performance at every level." },
  { category: "Management Accounting and Control",
    term: "Limiting factor",
    definition: "Anything which limits the activity of the entity." },
  { category: "Management Accounting and Control",
    term: "Management control",
    definition: "The process by which managers assure that resources are obtained and used effectively and efficiently in the accomplishment of the organization's objectives." },
  { category: "Management Accounting and Control",
    term: "Margin of safety",
    definition: "The difference in units between the budgeted sales volume and the breakeven sales volume. It is sometimes expressed as a percentage of the budgeted sales volume." },
  { category: "Management Accounting and Control",
    term: "Marginal cost",
    definition: "The variable cost of one unit of product or service." },
  { category: "Management Accounting and Control",
    term: "Market penetration pricing",
    definition: "Adopting a policy of low prices when a product is first launched to obtain sufficient penetration into a market." },
  { category: "Management Accounting and Control",
    term: "Market skimming",
    definition: "Involves charging high prices when a product is first launched and spending heavily on advertising and sales promotion to obtain sales." },
  { category: "Management Accounting and Control",
    term: "Opportunity cost",
    definition: "The value of the benefit sacrificed when one course of action is chosen in preference to an alternative." },
  { category: "Management Accounting and Control",
    term: "Outsourcing",
    definition: "The use of external suppliers as a source of finished products, components, or services. Also known as contract manufacturing or sub-contracting." },
  { category: "Management Accounting and Control",
    term: "Payback",
    definition: "The time required for the cash inflows from a capital investment project to equal the cash outflows." },
  { category: "Management Accounting and Control",
    term: "Post-Completion Audit (PCA)",
    definition: "An objective, independent assessment of the success of a capital project about the plan. It covers the whole life of the project and provides feedback to managers to aid the implementation and control of future projects." },
  { category: "Management Accounting and Control",
    term: "Price Elasticity of Demand",
    definition: "Measures the extent of change in demand for a product following a change to its price." },
  { category: "Management Accounting and Control",
    term: "Principal budget factor",
    definition: "The budgeted factor which limits the activities of an organization." },
  { category: "Management Accounting and Control",
    term: "Process costing",
    definition: "A form of costing applicable to continuous processes where process costs are attributed to the number of units produced." },
  { category: "Management Accounting and Control",
    term: "Production costs",
    definition: "The costs which are incurred by the sequence of operations beginning with the supply of raw materials and ending with the completion of the product ready for warehousing as a finished goods item." },
  { category: "Management Accounting and Control",
    term: "Profit center",
    definition: "Any section of an organization, for example, a division of a company, which earns revenue and incurs costs. The profitability of the section can therefore be measured." },
  { category: "Management Accounting and Control",
    term: "Relevant cost of an asset",
    definition: "Represents the amount of money that a company would have to receive if it were deprived of an asset to be no worse off than it already is." },
  { category: "Management Accounting and Control",
    term: "Relevant costs",
    definition: "Future cash flows arising as a direct consequence of a decision." },
  { category: "Management Accounting and Control",
    term: "Residual income (RI)",
    definition: "Pre-tax profits less a notional interest charge for invested capital." },
  { category: "Management Accounting and Control",
    term: "Responsibility accounting",
    definition: "A system of accounting that makes revenues and costs the responsibility of particular managers so that the performance of each part of the organization can be monitored and assessed." },
  { category: "Management Accounting and Control",
    term: "Responsibility center",
    definition: "A section of an organization that is headed by a manager who has direct responsibility for its performance." },
  { category: "Management Accounting and Control",
    term: "Return on capital employed (ROCE)",
    definition: "Also called Return on investment (ROI). Calculated as (profit/capital employed) × 100% and shows how much profit has been made about the amount of resources invested." },
  { category: "Management Accounting and Control",
    term: "Revenue center",
    definition: "A section of an organization that creates revenue but has no responsibility for production. A sales department is an example." },
  { category: "Management Accounting and Control",
    term: "Risk-averse",
    definition: "Decision-maker acts on the assumption that the worst outcome might occur." },
  { category: "Management Accounting and Control",
    term: "Risk neutral",
    definition: "The decision-maker is concerned with what will be the most likely outcome." },
  { category: "Management Accounting and Control",
    term: "Risk seeker",
    definition: "A decision-maker who is interested in the best outcomes no matter how small the chance that they may occur." },
  { category: "Management Accounting and Control",
    term: "Sales volume profit variance",
    definition: "The difference between the actual units sold and the budgeted (planned) quantity, valued at the standard profit per unit. It measures the increase or decrease in standard profit as a result of the sales volume being higher or lower than budgeted." },
  { category: "Management Accounting and Control",
    term: "Scrap",
    definition: "Discarded material having some value." },
  { category: "Management Accounting and Control",
    term: "Selling costs",
    definition: "Sometimes known as marketing costs, are the costs of creating demand for products and securing firm orders from customers." },
  { category: "Management Accounting and Control",
    term: "Selling price variance",
    definition: "A measure of the effect on expected profit of a different selling price to the standard selling price. It is calculated as the difference between what the sales revenue should have been for the actual quantity sold, and what it was." },
  { category: "Management Accounting and Control",
    term: "Semi-variable/semi-fixed/mixed cost",
    definition: "A cost that contains both fixed and variable components and so is partly affected by changes in the level of activity." },
  { category: "Management Accounting and Control",
    term: "Standard cost",
    definition: "A predetermined estimated unit cost, used for inventory valuation and control." },
  { category: "Management Accounting and Control",
    term: "Strategic information",
    definition: "Used by senior managers to plan the objectives of their organization and to assess whether the objectives are being met in practice." },
  { category: "Management Accounting and Control",
    term: "Strategic Management Accounting",
    definition: "A form of management accounting in which emphasis is placed on information which relates to factors external to the entity, as well as to non-financial information and internally generated information." },
  { category: "Management Accounting and Control",
    term: "Strategic planning",
    definition: "The process of deciding on objectives of the organization, on changes in these objectives, on the resources used to attain these objectives, and on the policies that are to govern the acquisition, use, and disposition of these resources." },
  { category: "Management Accounting and Control",
    term: "Strategy",
    definition: "A possible course of action that might enable an organization (or an individual) to achieve its objectives." },
  { category: "Management Accounting and Control",
    term: "Sunk cost",
    definition: "A past cost that is not directly relevant in decision making." },
  { category: "Management Accounting and Control",
    term: "Tactical information",
    definition: "Used by middle management to decide how the resources of the business should be employed, and to monitor how they are being and have been employed." },
  { category: "Management Accounting and Control",
    term: "Target costing approach",
    definition: "A process that begins with the development of a product concept and then the determination of the price customers would be willing to pay for that concept. The desired profit margin is deducted from the price, leaving a figure that represents total cost — the target cost." },
  { category: "Management Accounting and Control",
    term: "Total Quality Management (TQM)",
    definition: "A philosophy that means that quality management is the aim of every part of the organization. The aim is to 'get it right first time' which means that there is a striving for continuous improvement to eliminate faulty work and prevent mistakes." },
  { category: "Management Accounting and Control",
    term: "Value-added cost",
    definition: "Costs incurred for an activity that cannot be eliminated without the customer's perceiving a deterioration in the performance, function, or other quality of a product." },
  { category: "Management Accounting and Control",
    term: "Variable cost",
    definition: "A cost which tends to vary with the level of activity." },
  { category: "Management Accounting and Control",
    term: "Variable production overhead expenditure variance",
    definition: "The difference between the amount of variable production overhead that should have been incurred in the actual hours actively worked, and the actual amount of variable production overhead incurred." },
  { category: "Management Accounting and Control",
    term: "Variance",
    definition: "The difference between a planned, budgeted, or standard cost and the actual cost incurred." },
  { category: "Management Accounting and Control",
    term: "Weighted average cost method of inventory valuation",
    definition: "An inventory valuation method that calculates a weighted average cost of units produced from both opening inventory and units introduced in the current period." },
  { category: "Management Accounting and Control",
    term: "Zero-based budgeting (ZBB)",
    definition: "Involves preparing a budget for each cost center from a zero base. Every item of expenditure has to be justified in its entirety to be included in the next year's budget." },

  { category: "Law",
    term: "Abate",
    definition: "To end, eliminate, do away with, or make null and void." },
  { category: "Law",
    term: "Acceptance",
    definition: "The act of voluntarily agreeing, expressly or by implication, to the terms of an offer, creating a contract. However, if the act modifies or adds to the terms of the offer, it is not an acceptance, but a counteroffer." },
  { category: "Law",
    term: "Agency",
    definition: "A fiduciary relationship in which a person or entity acts, by mutual consent, for the benefit of another and binds the other party by words or deeds." },
  { category: "Law",
    term: "Agreement",
    definition: "A mutual understanding between two or more legally competent individuals or entities about their rights and duties regarding their past or future performances and consideration. While an agreement usually leads to a contract, it could also be an executed sale, a gift or other transfer of property, or a promise without a legal obligation." },
  { category: "Law",
    term: "Articles of incorporation",
    definition: "A written agreement setting forth the basic structure of a corporation. The document normally includes the name, duration, and purpose of the corporation; the names and addresses of its initial board of directors; and the number and classes of shares of stock that it will be allowed to issue." },
  { category: "Law",
    term: "Bad faith",
    definition: "Dishonesty of purpose; lack of fairness and honesty; the continuous and willful failure to fulfill one's duties or obligation." },
  { category: "Law",
    term: "Board of directors",
    definition: "The governing body of a corporation elected by the shareholders to establish and carry out corporate policy, select the corporation's officers, make certain major decisions concerning the corporation's business and finances, and to oversee the corporation's operations." },
  { category: "Law",
    term: "Breach of contract",
    definition: "A violation of a contract by either failing to perform one's contractual obligations or by interfering with another party's performance of their obligations." },
  { category: "Law",
    term: "Caveat emptor",
    definition: "Let the buyer beware. The legal principle that, unless the quality of a product is guaranteed in a warranty, the buyer purchases the product as it is and cannot hold another liable for any defects." },
  { category: "Law",
    term: "Contract",
    definition: "Any legally binding agreement voluntarily entered into by two or more parties that places an obligation on each party to do or not do something for one or more of the other parties and that gives each party the right to demand the performance of whatever is promised to them by the other parties." },
  { category: "Law",
    term: "Consideration",
    definition: "Something of value to either the promisee or the promisor of a contract (usually cash, but also property, a promise to do something or not to do something, and so on) that is given or will be given by the promisee to the promisor in exchange for a performance or a promise of a performance by the promisor." },
  { category: "Law",
    term: "Corporation",
    definition: "An entity, usually a business, created by a legislative act or by individuals who have agreed upon and filed articles of incorporation with the government. Ownership in the corporation is typically represented by shares of stock. A corporation is legally recognized as an artificial person whose existence is separate and distinct from that of its shareholders." },
  { category: "Law",
    term: "Copyright",
    definition: "The exclusive statutory right of literary, musical, visual, and other artists to control the reproduction, use, and disposition of their work, usually for their lifetime plus seventy years." },
  { category: "Law",
    term: "Damages",
    definition: "Financial compensation demanded by or directed by a court to be paid to a claimant as compensation for a financial loss or injury to person or property." },
  { category: "Law",
    term: "Fiduciary",
    definition: "An individual who owes another a legal duty of care and good faith in the management of a business, money, or property; for example, a corporate officer or the executor of a will." },
  { category: "Law",
    term: "Fraud (Law)",
    definition: "An intentional misrepresentation uttered to cause another to rely on it to his detriment." },
  { category: "Law",
    term: "Good faith",
    definition: "A party's state of mind in acting or carrying out an action or transaction, evincing honesty, fairness, full communication of any hidden issues or information, and an absence of intent to harm other individuals or parties to the transaction." },
  { category: "Law",
    term: "Negotiable instrument",
    definition: "Writing that meets certain criteria, such as that it contains an unconditional promise to pay a specified amount on demand or at a particular date to the bearer or a particular person, and it is signed by the person making it." },
  { category: "Law",
    term: "Partnership",
    definition: "A voluntary joining of two or more persons to jointly carry on and profit from a single business. A partnership is presumed to exist if the persons have agreed to proportionally share the losses and profits from that enterprise." },
  { category: "Law",
    term: "Power of attorney",
    definition: "A written instrument whereby someone is granted the right to perform certain acts as the agent of the grantor; that is, acting on the grantor's behalf." },
  { category: "Law",
    term: "Ratification",
    definition: "Affirmation or approval; adoption of an action that was done on one's behalf and treating that action as if it had been authorized by that person before the fact of it having been done." },
  { category: "Law",
    term: "Rescission",
    definition: "The termination of a contract unilaterally by a party for substantive legal reasons, such as the failure of the other party to perform its obligations; or, the mutual termination of a contract, with the result that both parties are restored to the status quo ante." },
  { category: "Law",
    term: "Shareholder",
    definition: "A person who owns one or more shares of stock in a joint-stock company or a corporation." },
  { category: "Law",
    term: "Ultra vires",
    definition: "Latin: Over, or outside of powers; that which is beyond a corporation's or an agency's authorized power." },
  { category: "Law",
    term: "Void",
    definition: "Of no legal effect; empty; unenforceable; provisions that do not have effect whatsoever." },
  { category: "Law",
    term: "Voidable",
    definition: "Able to be later voided or nullified; a valid act that may achieve what its purpose was until its fatal flaw is discovered or takes effect and causes it to be voided." },

  { category: "Tax",
    term: "Double taxation",
    definition: "Comes about when both taxes were imposed in the same taxable year for the same purpose, upon property owned by the same person within the territory and by the same taxing authority, or taxing twice for the same purpose, in the same year of the property in the territory in which tax is held." },
  { category: "Tax",
    term: "Economic benefit theory",
    definition: "The flow of wealth realized is taxable only to the extent that the taxpayer is economically benefitted." },
  { category: "Tax",
    term: "Realization theory",
    definition: "Revenue is generally recognized when both of the following conditions are met: (a) the earning process is complete or virtually complete, and (b) an exchange has taken place. This principle requires that revenue must be earned before it is recorded." },
  { category: "Tax",
    term: "Equity in taxation",
    definition: "This concept requires that apportionment must be more or less just in the light of taxpayers' ability to shoulder the tax burden and, if warranted, based on the benefits they received from the government or in proportion to the relative value of the taxable property." },
  { category: "Tax",
    term: "Shifting",
    definition: "The process of transferring the tax burden from the statutory taxpayer to another without violating the law." },
  { category: "Tax",
    term: "Situs of taxation",
    definition: "The place of taxation. The basic rule is that the state where the subject to be taxed as a situs may rightfully levy and collect the tax, and situs is necessarily in the state which has jurisdiction or which exercises dominion over the subject in question." },
  { category: "Tax",
    term: "Allowable deductions",
    definition: "These are matters of legislative grace and not a matter of right. A taxpayer can only deduct an item or amount from gross income if there is a law authorizing such a deduction." },
  { category: "Tax",
    term: "Calendar year",
    definition: "An accounting period of twelve months that ends on the last day of December." },
  { category: "Tax",
    term: "Fiscal year",
    definition: "An accounting period of twelve months that ends on the last day of any month other than December." },
  { category: "Tax",
    term: "Compensation income",
    definition: "All remuneration for services performed by an employee for his employer under an employer-employee relationship, unless specifically excluded." },
  { category: "Tax",
    term: "Fringe benefits",
    definition: "Any good, service or other benefit furnished or granted in cash or in-kind other than basic compensation, by an employer to an individual employee (except rank and file employee) such as housing, expense account, vehicle of any kind, household personnel, interest on loan at less than market rate, membership fees, and education assistance." },
  { category: "Tax",
    term: "Gross receipts",
    definition: "The total amount of money representing the contract price, compensation, service fee, rental or royalty, including the amount charged for materials supplied with the services, and deposits and advance payments actually or constructively received during the taxable period." },
  { category: "Tax",
    term: "Taxable income",
    definition: "Refers to the items of gross income specified in the Tax Code, less deductions, if any, authorized for such types of income by the Tax Code." },
  { category: "Tax",
    term: "Withholding tax at source",
    definition: "A payor corporation/person having the receipt, custody, control, or paying certain kinds of income or gains of an individual or corporation subject to tax is constituted as a 'withholding agent' of the BIR to deduct and withhold the tax on the income." },
  { category: "Tax",
    term: "Creditable withholding tax",
    definition: "A system intended to withhold taxes equally or at least approximate the tax due of the payee on certain income payments. These are not deemed full and final payment for income tax due on the income payments made by the payee." },
  { category: "Tax",
    term: "Final withholding",
    definition: "Constitutes full and final payment of the income tax due to the payee of said income. The payee is not required to file an income tax return for the particular income payment subject to a final withholding tax." },
  { category: "Tax",
    term: "Capital gain (loss)",
    definition: "The gain (loss) realized by a taxpayer from the sale, exchange, or other disposition of a capital asset." },
  { category: "Tax",
    term: "Capital gains tax",
    definition: "A final tax imposed upon capital gains presumed to have been realized from the sale, exchange, or other disposition of property located in the Philippines classified as capital assets, at the rate of 6% based on the gross selling price or zonal value or assessed value of the real property whichever is higher." },
  { category: "Tax",
    term: "VAT system",
    definition: "A method of imposing an ad valorem tax on value-added. The whole of the sales value of consumer goods or services is taxed by installments as the goods pass along the production and distribution chain involving successive transactions between businesses, but the tax is levied at each stage only on the value-added at one point." },
  { category: "Tax",
    term: "Zero-rated transactions",
    definition: "Transactions, either sale by VAT-registered persons or services performed in the Philippines by VAT-registered persons that are taxable subject to 0%. These are taxable transactions for purposes of VAT, but the seller is not liable to pay output tax." },
  { category: "Tax",
    term: "Estate Tax",
    definition: "A tax on the right to transfer property at death and on certain transfers which are made by law the equivalent of testamentary disposition, measured by the value of the property." },
  { category: "Tax",
    term: "Donor's tax",
    definition: "A tax imposed on the gratuitous transfer of property between two or more persons who are living at the time of transfer. It is neither a property tax nor a personal tax but a tax imposed on the right or privilege of the donor to make a gift." },
  { category: "Tax",
    term: "Assessment",
    definition: "Fixes and determines the tax liability of a taxpayer; it is also a demand made on the taxpayer concerned to settle the amount indicated in it. It signals the time when penalties and interests begin to accrue against the taxpayer." },
  { category: "Tax",
    term: "Vanishing deduction",
    definition: "An exclusive deduction from the gross estate allowed to minimize the harshness of double taxation, allowed on property left behind by the decedent which he had acquired previously by inheritance or donation from a prior decedent. The deduction diminishes over five years." },
];



